# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

header_pages:
  - README.md
  - setup.md
  - documentation.md

theme: minima
# remote_theme: pages-themes/minimal@v0.2.0